# Generated by Django 3.0.6 on 2020-05-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200510_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
    ]
