# Generated by Django 3.0.6 on 2020-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200510_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.CharField(default=None, max_length=150, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
