# Generated by Django 3.0.6 on 2020-05-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_publication_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
    ]
