# Generated by Django 3.0.6 on 2020-06-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200601_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
