# Generated by Django 3.0.6 on 2020-06-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
