# Generated by Django 3.0.6 on 2020-06-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=150, verbose_name='Аватар'),
        ),
    ]
