# Generated by Django 3.0.6 on 2020-06-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
