# Generated by Django 3.0.6 on 2020-06-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
