# Generated by Django 3.0.6 on 2020-07-19 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0033_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='post_dislike',
            field=models.ManyToManyField(blank=True, related_name='post_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='post_like',
            field=models.ManyToManyField(blank=True, related_name='post_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
