# Generated by Django 3.0.6 on 2020-07-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20200719_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='post_dislike',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='post_like',
        ),
    ]
