# Generated by Django 3.0.6 on 2020-07-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20200719_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарий'},
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
